### PR TITLE
Add Vietnamese locale

### PR DESCRIPTION
**Pull request by nhutdm**

### CODE REVIEW

**Comment by graysonwright** [comment]
Cảm ơn!

Can anyone from the community verify?

**Comment by joneslee85** [comment]
@graysonwright :+1: good to me.

**Comment by huydx** [comment]
:+1: 

LGTM

**Comment by graysonwright** [comment]
Great! Merged in as https://github.com/thoughtbot/administrate/commit/ee5fe3a6d33be5d3c19b3bb12d1a23bd1f779ef7. Thanks!

**Pull request closed without merging**
