### PR TITLE
Remove dependency on remote images in tests

### PR DESCRIPTION
**Pull request by pustomytnyk**
Fixes issue with images accessibility in tests (from #819). Issue can be reproduced with limiting internet bandwidth (test still pass if I've fully disabled internet).

### CODE REVIEW

**Comment by krzysiek1507** [comment]
Hi @pustomytnyk could you please rebase it? Thanks!

**Comment by nickcharlton** [comment]
Hi @pustomytnyk! If I could get you to fix the two Hound comments, I'd be happy to merge this.

**Comment by pustomytnyk** [comment]
updated.

> Why not just pass the options directly here?
Hound complained about line being too long (81/80).

**Comment by nickcharlton** [comment]
Got it, thanks! Merging.

**Pull request merged**
