### PR TITLE
Allow rails 5.1 usage

### PR DESCRIPTION
**Pull request by tiagoamaro**
Hello,

First, thank you very much for this gem! It's extremely useful, as its code is quite impressive and clean 🎉 very nice job!

This PR is my attempt to allow Rails 5.1 usage, while keeping the entire test suite green. There are some deprecation warnings, but they're related to `database_cleaner`:

```
DEPRECATION WARNING: schema_migrations_table_name is deprecated and will be removed from Rails 5.2 (called from block (2 levels) in <top (required)> at /Users/tiago/Projects/test_apps/administrate/spec/support/database_cleaner.rb:11)
```

Ran `bundle exec rake && bundle exec appraisal rake` and everything passed fine :)
Also, I'm currently using my fork on a project in production, and it seems to be working fine.

Note: I've noticed a PR to support Rails 5.1 (https://github.com/thoughtbot/administrate/pull/782), but it seems it's tackling more than just allowing this new Rails version to be used, so I decided to open this one.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
#782 was me trying to keep things up to date for a project as well. It's kinda me backporting stuff. I need to close it and reopen with a new PR. Thanks for tackling this!

**Comment by nickcharlton** [comment]
Thanks @tiagoamaro!

I'm not sure yet how I want to go about merging these two, but it's the focus for [`v0.8.0`][eight]. I'll be coming back to this soon!

[eight]: https://github.com/thoughtbot/administrate/milestone/8

**Comment by nickcharlton** [comment]
On #782, we were blocked by https://github.com/rails/sass-rails/pull/400, which was merged today. Does this help us at all here?

**Comment by nickcharlton** [comment]
The tests are failing because Rails 5 and up doesn't like unversioned migrations, so I'm going to worry about that in another PR and merge this. Thanks!

**Pull request merged**
