### PR TITLE
Fix #558 : Wrong constant name guess

### LINKED ISSUE #558: resource_class_name not working for every model name (Ie -> Y)
I have a model Ie, Administrate generate the controller (ies), routes, and dashboard properly, but when I visit 'admin/ies' I get:

```
uninitialized constant Y
```

I think the issue is located here:

https://github.com/thoughtbot/administrate/blob/master/lib/administrate/resource_resolver.rb#L15

"admin/ies".singularize #=> 'admin/y'
"ies".singularize #=> 'ie'

So #singularize must be call after split ant not before

### PR DESCRIPTION
**Pull request by jalberto**

### CODE REVIEW

**Comment by BenMorganIO** [comment]
@jalberto can you squash these commits and rebase? Would love to get this in :)

**Comment by jalberto** [comment]
@BenMorganIO done :)

**Comment by jalberto** [comment]
@BenMorganIO Any blocker on this? The CI error seem related to an internal TB url

**Comment by carlosramireziii** [comment]
@nickcharlton Have a look at this one.

**Comment by nickcharlton** [comment]
Looks good. Going to merge, thanks!

**Pull request merged**
