### PR TITLE
Update normalize.css and change how we include it

### PR DESCRIPTION
**Pull request by tysongach**
- Update normalize.css to v7.0.0.
- Include normalize.css as raw CSS, instead of through RubyGems because
  the normalize-rails gem has fallen much behing the release cycle of
  normalize.css.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
I deleted the @HoundCI comments since you marked that file as excluded (probably to avoid more Hound comments).

**Comment by tysongach** [comment]
> Should we place the normalize.css in the vendor folder instead of the app folder?

Good thinking! We don’t have a `vendor` directory in this project, currently. Is that something we can simply add and it will work given that this is a gem/generator? Or will we have to explicitly include it?

**Comment by BenMorganIO** [comment]
@tysongach Rails already loads up and checks for a vendor folder by default. So, you're all good.

**Comment by nickcharlton** [comment]
@BenMorganIO Is that still the case with a Rails Engine, though?

**Comment by BenMorganIO** [comment]
Errr... That's a good question. If we require it from administrate, it should still work... Administrate itself should be aware of a vendor folder. BUT an application should not be fully aware of Administrates vendor folder when it searches a tree. So, I'm going to say yes, but we should test that out. I could be completely wrong.

**Comment by tysongach** [comment]
What’s a good way to test that?

**Comment by BenMorganIO** [comment]
To test? Make sure normalize.css gets included 📦

**Comment by tysongach** [comment]
d4f5fb354030c1b9f7e616aa62db02394ab2dc4b places `normalize.css` in the `vendor` directory.

**Comment by nickcharlton** [comment]
I've tested this on a fresh Rails 5.1 app and it seems fine.

**Pull request merged**
