### PR TITLE
update redirect path after delete resource

### PR DESCRIPTION
**Pull request by jubilee2**
keep UI in the same page when delete has_many records in show page

### CODE REVIEW

**Comment by jubilee2** [comment]
only one thing I am not sure, the "redirect_back" method add to Rails start from Rails 5

**Comment by jubilee2** [comment]
we should guide people how to redirect back in after_resource_destroyed_path

https://github.com/rails/rails/blob/6-1-stable/actionpack/lib/action_controller/metal/redirecting.rb#L90

**Comment by pablobm** [comment]
Why did you close the PR? Regarding compatibility, Rails 6 is the oldest currently supported.

**Comment by jubilee2** [comment]
in the controller we have `after_resource_destroyed_path` to config the redirect path, in this PR I override the redirection order, make the `after_resource_destroyed_path` loss the meaning.

**Comment by pablobm** [comment]
Oh, I see. Makes sense :+1: 

Do you have any alternatives? Or perhaps the redirection path hooks should work differently?

**Pull request closed without merging**
