### PR TITLE
hasMany collection columns

### PR DESCRIPTION
**Pull request by jubilee2**
idea come from https://github.com/nickcharlton/administrate-field-nested_has_many/pull/54 but I use positive list not only skip the column but also can add/remove/order the columns.

### CODE REVIEW

**Review by pablobm — COMMENTED** [review]
Looks good! :slightly_smiling_face: Would you be able to add a test? I'm thinking a simple one would be to change the order dashboards to display the line items like this:

```ruby
    line_items: Field::HasMany.with_options(collection_attributes: [:product, :quantity, :unit_price, :total_price]),
```

Then you can check that the "Order" column doesn't appear. What do you think?

**Comment by jubilee2** [comment]
> Looks good! 🙂 Would you be able to add a test? I'm thinking a simple one would be to change the order dashboards to display the line items like this:
> 
> ```ruby
>     line_items: Field::HasMany.with_options(collection_attributes: [:product, :quantity, :unit_price, :total_price]),
> ```
> 
> Then you can check that the "Order" column doesn't appear. What do you think?

added

**Comment by pablobm** [comment]
Oof, build issue 😫 I think the issue is related to https://github.com/thoughtbot/administrate/pull/2410. Would you be able to rebase on top of the latest `main` and re-push?

**Comment by jubilee2** [comment]
> Oof, build issue 😫 I think the issue is related to #2410. Would you be able to rebase on top of the latest `main` and re-push?

merged main

**Comment by pablobm** [comment]
OK, let's go! 🚀 

Thank you for the contribution 🙂

**Pull request merged**
