### PR TITLE
Another year, another change to how to deal with webdrivers

### PR DESCRIPTION
**Pull request by pablobm**
Webdrivers breaking again (at least locally). Here's one of the fixes proposed at https://github.com/titusfortner/webdrivers/issues/247

### CODE REVIEW

**Comment by pablobm** [comment]
Grr. Version 4.11 requires Ruby 3. Will have to try an alternative option.

```
$ gem install selenium-webdriver:4.11.0
Fetching selenium-webdriver-4.11.0.gem
ERROR:  Error installing selenium-webdriver:
        There are no versions of selenium-webdriver (= 4.11.0) compatible with your Ruby & RubyGems
        selenium-webdriver requires Ruby version >= 3.0. The current ruby version is 2.7.6.219.
```

**Review by littleforest — COMMENTED** [review]
In other projects where I'm unable to upgrade selenium-webdriver past 4.9.0, I've been able to update webdrivers gem to 5.x and fix `Webdrivers::Chromedriver.required_version = "114.0.5735.90"`

**Comment by pablobm** [comment]
Pushed again to try the option suggested by @littleforest :hourglass:

**Comment by pablobm** [comment]
OK! CircleCI didn't make this trivial, but it appears to work :slightly_smiling_face:

**Review by littleforest — APPROVED** [review]
Yay!

**Pull request merged**
