### PR TITLE
Translate resource name for create link on index page.

### PR DESCRIPTION
**Pull request by Samemura**
I am using administrate in ja local and realize resource name is not translated.
Can we replace it with translated ?

Place I meant here. (It is en local but)
image

### CODE REVIEW

**Comment by Samemura** [comment]
@nickcharlton Hello! Can you review this PR, please ? If OK, I will fix Circle CI error(nokogiri version error).

**Comment by nickcharlton** [comment]
I just rebased this to catch up with it; where does `class_from_resource` come from?

**Comment by pablobm** [comment]
I believe this is the same as https://github.com/thoughtbot/administrate/pull/1777

**Comment by nickcharlton** [comment]
Oh yes, you're right. I'm going to close this.

**Pull request closed without merging**
