### PR TITLE
Support Rails 5+ attributes api for virtual attributes

### PR DESCRIPTION
**Pull request by excid3**
This adds support for the Rails 5 attributes API allowing you to add virtual attributes with types to ActiveModel objects.

I ran into the error in #1100 because of an Rails 5 attribute I had on my model so I wrote this fix for that. It might also solve the issues the other people were experiencing, I'm not sure.

### CODE REVIEW

**Comment by CaioBianchi** [comment]
Please, accept this PR. Rails 5.2 introduced Attributes, and it'd be nice if Administrate didn't choke on it.

**Comment by ryanlitalien** [comment]
@nickcharlton @nickcharlton @composerinteralia Could we please get some 👀on this pull request and merge if ok please? I'd really like to use Administrate for our 5.2 Rails project.

**Comment by excid3** [comment]
Nudge @nickcharlton :)

**Comment by composerinteralia** [comment]
Hey all, we are not intentionally ignoring this PR. There are just a lot of open issues and PRs and we haven't had time to review. We will get to this eventually, but it may take some time.

**Comment by excid3** [comment]
This now directly conflicts with 4e36c31be4e30ca9474397a9e079b6501bb22c50 which explicitly looks at columns now instead of attributes.

**Pull request closed without merging**
