### PR TITLE
Fix broken link in Customizing Search guide

### PR DESCRIPTION
**Pull request by cabe56**
Administrate demo app link pointed to /admin instead of /spec/example_app

### CODE REVIEW

**Comment by cabe56** [comment]
Check breaking seems unrelated to the files changed:
Screen Shot 2022-08-16 at 8 09 31 PM

**Comment by cabe56** [comment]
@pablobm can you merge this? Small change to fix a broken link

**Comment by pablobm** [comment]
So this link is not really what you think it is :slightly_smiling_face: It is intended for people who visit https://administrate-demo.herokuapp.com/ They can click on it and visit the demo site online.

I also think that that page is not a good place to mention that the demo app is located in such directory of the codebase. I wonder if it makes sense to instead create a new section "The Demo App" to appear on the sidebar under "Documentation", and use it to explain the demo app briefly and mention that it can be found at `spec/example_app`. What do you think?

**Comment by pablobm** [comment]
Closing due to lack of activity

**Pull request closed without merging**
