### PR TITLE
Change Albanian two-letter code to "sq" as per ISO 639-1

### PR DESCRIPTION
**Pull request by pustomytnyk**
It would be logical if language codes correspond ISO 639-1.

### CODE REVIEW

**Comment by nickcharlton** [comment]
Do you know if there's a reason that it was originally `al`?

**Comment by pablobm** [comment]
Looks like `al` is the code for the country, while `sq` is the code for the language. No idea of how this plays into locales.

Looking at https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html, I see that the language tag is `sq-AL`. Comparing this with something else like `es-AR`, then I would infer that `sq` is the correct one to go with. But I can't tell for certain.

The original author of this file is @acelina (see https://github.com/thoughtbot/administrate/pull/1117). I wonder if he could shed some light into this?

**Comment by acelina** [comment]
Hello. Yes, correct one to go is sq. That's the ISO code for the language. Apologies for the mistake that slipped through.

**Comment by pablobm** [comment]
Thank you. @pustomytnyk, would you be able to rebase and push this? The build failed, and I think it's just a glitch that has been solved since.

**Comment by pablobm** [comment]
OK, I tried running CI of this on my repo and it passed, so I'm going to try and merge this :crossed_fingers:

**Comment by pablobm** [comment]
That worked! :D

**Pull request merged**
