### PR TITLE
allow new action accept params

### PR DESCRIPTION
**Pull request by lazing**
allow new action accept params

### CODE REVIEW

**Comment by graysonwright** [comment]
Hey, @lazing! Thanks for the contribution. I have a couple questions:

- How will you pass values into the request?
- What will this feature look like from the user's perspective?

**Comment by lazing** [comment]
Hey, @graysonwright here is my scenario:
i want create order for specific user, and i got lots of users(10000+).
so i need to search and locate a user, open the show page and click `create order`.

The link with the params `order: {user_id: xxx}`, so the order is related to the user

**Comment by nickcharlton** [comment]
Hi @lazing!

I'm just coming to your PR for real now. Could you clarify how this would be used? I don't feel like I understand from your example.

Would you also be able to rebase this on top of `master`?

**Comment by nickcharlton** [comment]
Closing as it's been a while since the last response.

**Pull request closed without merging**
