### PR TITLE
paginate? should return boolean

### PR DESCRIPTION
**Pull request by jubilee2**
fix #2289

### CODE REVIEW

**Comment by pablobm** [comment]
Thank you!

**Comment by pablobm** [comment]
Oh, wait. I thought this was a PR on main :sweat: I'll fix it...

**Comment by pablobm** [comment]
@jubilee2 - Next time, please leave this as a suggestion in a PR comment. I was quite confused there! :sweat_smile:

**Comment by jubilee2** [comment]
I was trying To do that but it says I do not have permission. You can use crash merge this time if want to keep clean commit

**Comment by pablobm** [comment]
@jubilee2 - oh, i didn't realise. Apologies.

**Pull request merged**
