### PR TITLE
feat: refactor page redirect target path

### PR DESCRIPTION
**Pull request by saiqulhaq**
this will make us easier to override redirect path

should I make test & update the doc?

### CODE REVIEW

**Review by pablobm — COMMENTED** [review]
This looks good! Yes, please provide specs and docs.

For the specs, I think the simplest way would be to create a file `spec/controllers/admin/application_controller_spec.rb` and use the "Anonymous controller" feature of RSpec: https://relishapp.com/rspec/rspec-rails/v/5-0/docs/controller-specs/anonymous-controller

Let me know if you have any questions.

**Comment by edimossilva** [comment]
@saiqulhaq and @pablobm , can I provide specs and docs for this PR?

**Comment by saiqulhaq** [comment]
yes please
I have no available time to provide it

**Comment by pablobm** [comment]
Continued at https://github.com/thoughtbot/administrate/pull/1995

**Pull request closed without merging**
