### PR TITLE
Add support for swedish locale

### PR DESCRIPTION
**Pull request by talltorp**
This commit adds swedish translations to Administrate.

### CODE REVIEW

**Comment by graysonwright** [comment]
Continued from #262.

@talltorp, tack!

In the future, if you need to make corrections to the file, you can add them to this existing PR instead of creating a new one - just push your new commits onto the master branch of your own repository, and they'll show up here in this PR.

@teoljungberg, can you verify this? Thanks!

**Comment by calleerlandsson** [comment]
Looks good to me!

**Comment by graysonwright** [comment]
@talltorp and @calleerlandsson, thanks!!

Merged in as 3e0acb2.

**Comment by talltorp** [comment]
Thanks for the tip, @graysonwright :+1: 

I wanted the PR to only contain one commit, since it was only one real change.

**Comment by graysonwright** [comment]
@talltorp we've been using `git rebase` ([reference](http://www.git-scm.com/book/en/v2/Git-Branching-Rebasing)) to combine multiple commits into a single one when we merge PRs.

**Comment by talltorp** [comment]
So the proper way for this would be to

1. Make the initial commit (which had the error in it)
2. Fix the small error in a separate commit
3. Wait for the PR to be accepted
4. Rebase my fork (and squash the commits into one)
5. Force push my changes
6. You merge the "clean" branch

Or would you do 4, 5 and 6?

**Comment by graysonwright** [comment]
@talltorp yep, that's the process.

We've been taking care of 4,5, and 6, because it seems to speed up the contribution cycle. We usually sneak in a `CHANGELOG.md` edit in there while we're at it.

**Pull request closed without merging**
