### PR TITLE
Dev setup fixes

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Hi, congrats for administrate, it's great!

I wanted to contribute a real improvement, but I had some trouble setting up the environment since I couldn't get the tests passing. I don't know why this is not reproduced in CI...

The changes:
- Use truncation instead of deletion strategy for `DatabaseCleaner` since it's not affected by foreign key constraints. https://github.com/thoughtbot/administrate/commit/919fc191ae49d01e33d66580f273388ae292fb64
- Remove some confusing output from one script. https://github.com/thoughtbot/administrate/commit/0c1bdd6b0739e84fd0f72b176239a0421b11e629

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Hey, I love 919fc19, but can you paste an example of the errors you got from c490e73? I'm a bit shy of hiding errors. Maybe adding a message telling the developer to ignore a specific error would be better, instead of blacklisting them.

**Comment by deivid-rodriguez** [comment]
@BenMorganIO Regarding https://github.com/thoughtbot/administrate/commit/919fc191ae49d01e33d66580f273388ae292fb64, well, errors are not actually being ignored. The status code of the resulting command is used to decide what to do.

Regarding, c490e73, I copied one of the errors inside the commit message.

**Comment by deivid-rodriguez** [comment]
@BenMorganIO Sorry, totally misunderstood your message. Let me show the errors you're asking for.

**Comment by deivid-rodriguez** [comment]
After a closer look, I think the old code was not printing expected errors but actually doing the wrong thing.

This is the output before my changes

```
...
You are a collaborator on the "administrate-prototype-staging" Heroku app
You are a collaborator on the "administrate-prototype-production" Heroku app
Joining administrate-prototype-production... Joining administrate-prototype-staging... !!!
 ▸    App not found.
!!!
 ▸    App not found.

```

This is the output after

```
...
Ask for access to the "administrate-prototype-staging" Heroku app
Ask for access to the "administrate-prototype-production" Heroku app
```

Not sure about what's going on but the second looks more correct... I can dig in a bit more if you want.

**Comment by BenMorganIO** [comment]
Well, the second message looks a lot more informative than the first. I'm :+1: on c490e73.

**Comment by deivid-rodriguez** [comment]
@BenMorganIO @nickcharlton I dusted off this old PR since I run into the same problems again.

* Added a few extra improvements on the setup.
* Finally found the reason for the bad errors messages in `bin/setup`: `&>` is a bash-only construct. So there's an alternative to https://github.com/thoughtbot/administrate/pull/578/commits/f9777691f2e22ca33226a40900e347046673ba30 which is changing the shebang from `#!/usr/bin/env sh` to `#!/usr/bin/env bash`. Let me know which one is you prefer.

**Comment by nickcharlton** [comment]
Hi @deivid-rodriguez!

I like this! I'm very much a fan of keeping it non-bash specific, too.

re [`f977769`](https://github.com/thoughtbot/administrate/pull/578/commits/f9777691f2e22ca33226a40900e347046673ba30): is it possible that this could be contributed back up to [suspenders](https://github.com/thoughtbot/suspenders) too (it's possible it was already fixed, but this is where this would have come from)?

I'm going to merge this.

**Comment by deivid-rodriguez** [comment]
Done: https://github.com/thoughtbot/suspenders/pull/820

Thanks! :heart: :yellow_heart: :purple_heart:

**Pull request merged**
