### PR TITLE
Normalize resource params

### PR DESCRIPTION
**Pull request by jakesen**
This provides a solution for issues like these: https://github.com/thoughtbot/administrate/issues/441

The solution is provided by allowing each field class to decide how to handle empty values via a normalize class method. A substitute value can be specified with an `empty_value` option when initializing a field using `with_options`.

This PR should probably have a little more test coverage, but first I want to see what adjustments might need to be made to the implementation to make it acceptable.

### CODE REVIEW

**Comment by jakesen** [comment]
Hmmm. Hound isn't leaving any comments to indicate why it is failing.

**Comment by carlosramireziii** [comment]
@jakesen Would you consider doing a narrower PR which just focused on the solution suggested in #441?

> It makes sense to me to nil those values out. If you want to take a crack at that, go ahead. Otherwise it's going to sit a bit - I'm a bit backed up with issues at the moment.

You would be able to add the necessary test coverage and perhaps that would make it an easier merge.

**Comment by jakesen** [comment]
Yeah. I think that will work for what we're doing. I'll close this and do a new PR with the narrower scope.

**Comment by akestner** [comment]
@jakesen You ever get around to a more narrowly-scoped PR?  I'd consider taking a stab at it if you haven't.

**Comment by jakesen** [comment]
@akestner I haven't got around to it but I would be happy to collaborate on a good solution. You might want to weigh in on the conversation over at https://github.com/thoughtbot/administrate/issues/441 WRT which types of fields and what default behavior is desired.

**Pull request closed without merging**
