### PR TITLE
Clear dt.attribute-label past left-floated elements

### LINKED ISSUE #230: Show page: wrapped attribute-label combined with empty attribute-data breaks rendering.
When an attribute-label is long and wraps to a second line, and when the corresponding attribute-data element is empty, the next attribute-label doesn't clear to a new line, but bumps up against the previous label:

screen shot 2015-11-12 at 3 46 00 pm

Seen on Chrome Version 46.0.2490.86 (64-bit) / OSX 10.10.5

### PR DESCRIPTION
**Pull request by calumhalcrow**
Fixes #230

### CODE REVIEW

**Comment by graysonwright** [comment]
@calumhalcrow I just merged #188, which adds visual regression testing. I'd like to  run all CSS/HTML changes through that test.

Would you mind rebasing on top of master so this can run through those tests? Thanks!

**Comment by calumhalcrow** [comment]
@graysonwright I have rebased onto master and it appears that tests pass (although maybe that in itself is a problem since this change can change the UI visibly?).

BTW, as a side-note: when I run tests locally (after following the [Contributing](https://github.com/thoughtbot/administrate/blob/master/CONTRIBUTING.md) guide), I get an error:

```
$ bundle exec appraisal rake
>> BUNDLE_GEMFILE=/Users/calum/Projects/administrate/gemfiles/sass_3_4.gemfile bundle exec rake
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/Users/calum/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- percy/capybara/rspec (LoadError)
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /Users/calum/Projects/administrate/spec/rails_helper.rb:10:in `<top (required)>'
	from /Users/calum/Projects/administrate/spec/administrate/views/fields/has_many/_show_spec.rb:1:in `require'
	from /Users/calum/Projects/administrate/spec/administrate/views/fields/has_many/_show_spec.rb:1:in `<top (required)>'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<main>'
/Users/calum/.rvm/rubies/ruby-2.2.0/bin/ruby -I/Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/lib:/Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-support-3.1.2/lib /Users/calum/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I was able to fix it with this change:
```
$ git diff
diff --git a/gemfiles/sass_3_4.gemfile b/gemfiles/sass_3_4.gemfile
index b8c658f..622e42b 100644
--- a/gemfiles/sass_3_4.gemfile
+++ b/gemfiles/sass_3_4.gemfile
@@ -37,6 +37,7 @@ group :test do
   gem "shoulda-matchers", "~> 2.8.0", :require => false
   gem "timecop"
   gem "webmock"
+  gem "percy-capybara"
 end

 group :staging, :production do
```
I'm not sure if this is the appropriate thing to do though. Should I open a PR?

**Comment by graysonwright** [comment]
@calumhalcrow Looks like that gemfile was fixed in 079c17fc - rebasing again should sort it out.

I'm curious why the build on CircleCI doesn't fail for that - it would be much easier to keep our Appraisal gemfiles up-to-date if we had feedback on that.

**Comment by calumhalcrow** [comment]
@graysonwright I have rebased. Tests pass locally for me, but CircleCI is failing due to what seems a setup issue on their end:

"Your Ruby version is 2.2.0, but your Gemfile specified 2.2.3"

**Comment by graysonwright** [comment]
@calumhalcrow yeah, I saw that error last night. We're working on a fix in #253.

**Comment by graysonwright** [comment]
Looks like it's fixed - we just needed to re-run the tests without the cache.

**Comment by graysonwright** [comment]
This looks good!

It would be great to have a test for this case, but without being able to customize labels for a field it'll be fairly difficult to set up the test case. I'm okay skipping the test for now.

**Comment by graysonwright** [comment]
Merged in as a847d57. Cheers!

**Pull request closed without merging**
