### PR TITLE
Make it easier to override variables

### PR DESCRIPTION
**Pull request by To1ne**
Add the `!default` flag to all the variables, this makes it easier override the colors.
[More info about `!default`](https://robots.thoughtbot.com/sass-default)

### CODE REVIEW

**Comment by tysongach** [comment]
@To1ne Would you mind rebasing this on `master`?

**Comment by To1ne** [comment]
@tysongach Done!

**Comment by tysongach** [comment]
@To1ne Sorry, do you mind rebasing once more? Then this should be ready, @nickcharlton!

**Comment by To1ne** [comment]
@tysongach @nickcharlton Done!

**Comment by tysongach** [comment]
Thanks, @To1ne!

**Pull request merged**
