### PR TITLE
Allow customizing the layout's header

### PR DESCRIPTION
**Pull request by FooBarWidget**
This pull request allows one to customize the `<head>` tag on a per-page basis, e.g. to insert custom style sheets.

### CODE REVIEW

**Comment by Tensho** [comment]
Actually, the similar hook will be nice to have for nav bar (display authentication info), for example. Unfortunately, as a gem user, I can't inject `content_for` inside the engine layout within Rails nested layout mechanism. Probably, the only resonable way is layout coping from gem to the application right now, because we can't predict all possible use cases.
@graysonwright, Do you have a common strategy to extend administrate `application.html.erb` layout? Particularly, it's quite reasonable to keep hook like `page_head`, but what about other stuff?

**Comment by Tensho** [comment]
Sorry, found [this](https://github.com/thoughtbot/administrate/issues/258) conversation with explenations.

**Comment by carlosramireziii** [comment]
@Tensho Is the application layout generator sufficient to resolve your problem? Do you prefer the solution in this PR?

**Comment by nickcharlton** [comment]
Thanks for your PR! I'm going to close this as the activity has been low and there's a potential (linked) solution.

**Pull request closed without merging**
