### PR TITLE
administrate engine requires bourbon. fixes #615

### LINKED ISSUE #615: Dependency on bourbon not listed
After upgrading to administrate 0.2.2 (from 0.2.0) my app started throwing:

```
File to import not found or unreadable: bourbon.
[snip]
./app/views/layouts/application.html.haml:8:in `_app_views_layouts_application_html_haml___2930206960703904785_47038691733580'
```

This was fixed by adding the 'bourbon' gem to my Gemfile, but I feel it should properly be included in administrate's dependencies instead.

### PR DESCRIPTION
**Pull request by kpheasey**
Continued from https://github.com/thoughtbot/administrate/pull/673

### CODE REVIEW

**Comment by kpheasey** [comment]
> Good point. It looks like we have some dependencies just in the Gemfile, some just in the gemspec, and some in both. Not sure why that happened.
> 
> Do you want turn this PR into a migration from using the Gemfile to using the gemspec? Doing that should both fix the bourbon problem and fail the specs when not requiring he proper files.

@JoelQ I don't know enough about administrate to turn the gemfile into a gemspec.  The dependencies need to be explicit version ranges.  Additionally, I wouldn't know what to do about the staging/production requirements.

**Comment by nickcharlton** [comment]
Thanks for this! I'm electing to pick just the `bourbon` for now, we'll target others as they happen.

**Comment by jipiboily** [comment]
Seems like it's still an issue, right? Or was just never shipped?

**Comment by klaseskilson** [comment]
@jipiboily This fix hasn't been released yet. It will once `> 0.3.0` is released. If you need the fix earlier, point your Gemfile entry towards Github, like so: 

```ruby
gem 'administrate', git: 'https://github.com/thoughtbot/administrate.git'
```

**Comment by jipiboily** [comment]
Thanks for the confirmation. That's what I just did a couple of minutes ago. It felt weird that it was not released 2 months later, so I wanted to double check :) Thanks!

**Comment by pedantic-git** [comment]
@kpheasey @nickcharlton - there are issues with moving to Bourbon 5 because it no longer ships with an Engine and instead has a generator to add the SCSS files into your asset pipeline.

Which means that if you're using administrate in a project that doesn't use Bourbon (and therefore has not run the generator) you get "File to import not found or unreadable: bourbon".

I think either Administrate needs to ship with the Bourbon 5 SCSS already in its vendor/stylesheets or it needs to remove its dependency on Bourbon, which shouldn't be too hard?

**Pull request merged**
