### PR TITLE
Products also need to destroy dependent models.

### PR DESCRIPTION
**Pull request by nickcharlton**
This is related to #739 and #738.

### CODE REVIEW

**Comment by danbee** [comment]
Is this actually desired though? In a normal online store you'd want historic orders to maintain a record of the products that were actually ordered.

**Comment by nickcharlton** [comment]
In an actual store, no.

So we could either do this to avoid getting a 500 when someone tries deleting, adjust the demo data model to take that into account or have an error message. As it's just a demo, this is an easier way of solving that.

**Comment by danbee** [comment]
Given that this is a demo this is a reasonable approach. Although we could mark the products as deleted instead which would solve the `line_item` association problem in a way that would be more in line with how a real store would do it.

**Comment by nickcharlton** [comment]
Yeah, I'm wondering now if we shouldn't use it being a demo as an excuse and instead do it properly.

**Comment by BenMorganIO** [comment]
In theory, line items should be "destroyed" when orders are destroyed; although orders should never be destroyed (especially completed ones). Paranoia would be great for archiving the products.

But this is just a demo and I feel it'd be a tad bit too much. I'm :+1: for this. Another alternative could be to nullify the foreign key, rather than cascade.

**Pull request merged**
