### PR TITLE
Use ActiveModel::Naming.route_key in sidebar link_to

### PR DESCRIPTION
**Pull request by tmecklem**
This fixes the ActionController::UrlGenerationError thrown when the
sidebar partial tries to render index links on models which have an
uncountable inflection.

### CODE REVIEW

**Comment by tmecklem** [comment]
Can I get a response for this PR? I'm can't keep updating it indefinitely. Seems like it's still a solution for issue #400 and it's still affecting people.

**Comment by carlosramireziii** [comment]
@nickcharlton We'll need to look into this one

**Comment by nickcharlton** [comment]
Hi @tmecklem! Sorry, I've just noticed this. I think this would be good to go, if I could trouble you to rebase again?

**Comment by nickcharlton** [comment]
I've taken this PR, rebased it and opened #934. I'm going to close this, as the other will go in soon.

**Pull request closed without merging**
