### PR TITLE
Abstract model classes should be skipped without warning.

### PR DESCRIPTION
**Pull request by lukeredpath**
I’ve also clarified the existing specs by including an assertion against the presence of a warning, so the name of the spec matches what is actually being tested.

I'm not 100% happy with checking against an exact match on the warning text but it seemed important to check for the presence (or absence) of a warning.

This is related to #581 but I'm not sure its the only issue I'm having with this generator on Rails 5.

### CODE REVIEW

**Comment by BenMorganIO** [comment]
@lukeredpath totally want to get this merged. Can you rebase and squash 8e945d6 and 4551dc6 into a single commit? You could also use heredocs to help shorten the strings; or multilines with `\`. :)

**Comment by carlosramireziii** [comment]
@lukeredpath Just wanted to check in on this one.. Would you be able to take care of the feedback from above? We'd love to get this one merged. Thanks!

**Comment by nickcharlton** [comment]
@lukeredpath Could I get you to fix up the Hound warnings on this and rebase? Or alternatively, [enable contributor pushes](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by nickcharlton** [comment]
I'm going to close this as I've rebased myself and opened #857.

**Pull request closed without merging**
