### PR TITLE
Support namespaced models

### LINKED ISSUE #179: How to use with namespaced models.
I have a user model that lives in Platform::User..   I ran the generator with administrate::dashboard Platform::User and this created a user_dashboard.rb and a users_controller.rb..     when I try to go to the users page in admin it fails saying 

```
uninitialized constant Admin::Platform
```

it points to this line in the controller: 

``` ruby
class Admin::Platform::UsersController < Admin::ApplicationController
```

I tried to remove the Platform:: from the controller and dashboard file but that just produced a similar error but this time saying User was an uninitiatized constant.

thanks!
Gary

### PR DESCRIPTION
**Pull request by trekdemo**
I tried to fix #179 with the least change in the current code.

@graysonwright I didn't look into the projects source too deep, so I might broke some parts that are not covered with tests if there are any. 
Can you give some hints if something else needs to be done?

### CODE REVIEW

**Comment by trekdemo** [comment]
@graysonwright can I do something to fix HoundCI checks?

**Comment by ACPK** [comment]
+1

**Comment by ACPK** [comment]
@graysonwright @trekdemo Any progress on this as this is the #1 issue for me.

**Comment by trekdemo** [comment]
With the [0.6.0](https://github.com/thoughtbot/administrate/releases/tag/v0.6.0) release I'm closing this one.

**Pull request closed without merging**
