### PR TITLE
Add button to clear search field

### LINKED ISSUE #121: Feature Request: Clearing Search
I'd love to be able to easily the clear search by (1) deleting the text or (2) clicking an (X). As of right now, a user needs to click the page link in the navbar or remove the params for the URL. The former is my preferred method, but let me know what you think.

### PR DESCRIPTION
**Pull request by graysonwright**
Closes #121.

## Problem:

Users cannot clear their search
unless they re-submit the search with an empty field,
or click on the resource link in the navigation bar.

## Solution:

Add a button for clearing out the search field
and going back to showing all resources.

customers___administrate_prototype

## To Do

- [ ] Only show clear icon when there is text in the search bar
- [ ] CHANGELOG

### CODE REVIEW

**Comment by danbee** [comment]
Can I suggest actually putting a button with the word "Clear" on it? Currently it looks a little like a close button.

**Comment by danbee** [comment]
On reading back I realise my last comment sounded a bit rude. Wasn't meant to be!

**Comment by graysonwright** [comment]
@danbee no, you're fine! Would it be better if the X only appeared when there's text in the box? The fading in might give the user context about its meaning.

I'll try it with "Clear" and add a screenshot as well.

**Comment by danbee** [comment]
Search boxes on Mac's tend to use a cross in a little circle. I'm just knocking up an SVG now to see what it looks like.

**Comment by danbee** [comment]
How about this?

screen shot 2015-11-02 at 17 26 44

**Comment by danbee** [comment]
I think it does make sense for the clear button to only appear when there is text in the search box. This mirrors the way I've seen search boxes work elsewhere.

**Comment by ACPK** [comment]
@danbee @graysonwright This is exactly what I was looking for!

**Comment by graysonwright** [comment]
@danbee I like it - did you make that icon?

I've been making custom icons for administrate so far, to avoid copyright issues. If you got that from somewhere, we should check the license or I can just make one up.

**Comment by danbee** [comment]
I made it myself. Did it by scaling down the existing one and putting a circle around it. I'm not 100% happy with it though so let me make a better one.

**Comment by ACPK** [comment]
@graysonwright Will this be getting pushed?

**Comment by zamith** [comment]
What about using the [input type search](http://caniuse.com/#feat=input-search)?

**Comment by danbee** [comment]
`input type="search"` can be a pain to style.

**Comment by zamith** [comment]
@danbee And do we really need to style that?

**Comment by danbee** [comment]
@zamith To fit the current layout, yes.

**Comment by danbee** [comment]
Also, the default styling is very inconsistent between different browsers. Safari, for instance, has it's own magic CSS incantations to style certain aspects of it.

**Comment by ACPK** [comment]
What ever happened to this?

**Pull request merged**
