### PR TITLE
HasMany: Allow :scope option

### PR DESCRIPTION
**Pull request by benoror**
Closes https://github.com/thoughtbot/administrate/issues/1988

### CODE REVIEW

**Comment by pablobm** [comment]
Hello @benoror, thank you for this. Could you please clean the Hound warning and add an spec example, and I'll merge this?

For the spec, I suggest that you have a look at the one for `BelongsTo` for an idea of how to do it.

**Comment by benoror** [comment]
@pablobm I ended using this extension, do you think it's worth it baking it into Administrate (maybe it is)? 
https://github.com/thoughtbot/administrate/issues/1988#issuecomment-1254477303

**Comment by pablobm** [comment]
Initially, I prefer not baking the suggested plugin into Administrate. There are some improvements that can be made to fields, and adding blocks like this is one of them, but it needs thinking a bit more about what the arguments would be. For example, I would like the fields to know more about the current request (current user, etc) so that values can be customised per-request (and per-user, etc), so I would prefer not changing that just now.

**Comment by pablobm** [comment]
If the plugin is enough for you, I'll close this. Happy to reopen and merge (after the Hound warning is resolved) if you still want to do it though.

**Comment by benoror** [comment]
Hey @pablobm, the plugin has worked for me so far, all good closing this for now. Thanks!

**Pull request closed without merging**
