### PR TITLE
Punditize add support for namespaced models and base policy fallbacks

### LINKED ISSUE #1332: Authorization with Pundit doesn't allow Policy Namespacing
[Punditize](https://github.com/thoughtbot/administrate/blob/b85abcf965ecc843ee9b25e3a2ea65dfeb1b0b3c/app/controllers/concerns/administrate/punditize.rb) assumes that there is no Pundit [Policy Namespacing](https://github.com/varvet/pundit#policy-namespacing) being used. If we allow namespaces, we could even avoid the custom policy_scope_admin.

Quick work around is, instead of including Punditize, to use the following code:

```
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Pundit

    def policy_scope(scope)
      super([:admin, scope])
    end

    def authorize(record, query = nil)
      super([:admin, record], query)
    end

    def scoped_resource
      policy_scope super
    end

    def authorize_resource(resource)
      authorize resource
    end

    def show_action?(action, resource)
      Pundit.policy!(pundit_user, [:admin, resource]).send("#{action}?".to_sym)
    end

  end
end

```

### PR DESCRIPTION
**Pull request by sedubois**
See https://github.com/thoughtbot/administrate/pull/1591#issuecomment-638218493

Fixes #1332.

### CODE REVIEW

**Comment by pablobm** [comment]
I think this is good. I haven't used this that much, but I think that `policy_admin` should be removed, as the same functionality can be achieved more naturally from a controller. Unless I'm missing something...?

One problem though is that some people may rely on `policy_admin`. We should still support it, with a warning, and then remove it in a future version (not the next version).

**Comment by pablobm** [comment]
@sedubois - As mentioned above, would you be able to add back `policy_scope_admin`, making it issue a deprecation warning on usage?

**Comment by nickcharlton** [comment]
@sedubois, re: @pablobm's comment above, would you be able to do that? I think rebasing too will get rid of the CI errors as those are things I've seen before. Then we should be good to go.

**Comment by sedubois** [comment]
@pablobm @nickcharlton I'm still happy to get back to this and a couple of other PRs but I'm a bit swamped ATM. I'd suggest leaving on my plate unless of course someone feels like taking over.

**Comment by nickcharlton** [comment]
That's perfect, thanks! I'll leave it to you to get back to when you can.

**Comment by pablobm** [comment]
Looks like there's renewed interest on this PR? If someone picks this up and implements the proposed tweaks above, that would be great. For an example of how to issue warnings within Administrate, see: https://github.com/thoughtbot/administrate/blob/master/lib/administrate.rb

**Comment by pablobm** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
