### PR TITLE
Add Dutch translations

### PR DESCRIPTION
**Pull request by Marthyn**

### CODE REVIEW

**Comment by graysonwright** [comment]
Met dank!

Anyone from the community want to verify?

**Comment by Marthyn** [comment]
Geen dank ;)

I was only doubting if i should've used the formal or informal 'you' in are you sure. Right now it's the formal, 'u'.

**Comment by jessieay** [comment]
um what this is awesome :100:

**Comment by graysonwright** [comment]
Jessie! You speak Dutch?

**Comment by jessieay** [comment]
I took a semester of German in 6th grade. So YES

**Comment by jessieay** [comment]
(ok...so no. I just think it's awesome that administrate already has a dutch translation)

**Comment by graysonwright** [comment]
:smile:

**Comment by Marthyn** [comment]
Lots of fans of Thoughtbot here ;)

**Comment by Marthyn** [comment]
Also, if you wanna learn https://www.duolingo.com/course/nl-NL/en/Learn-Dutch-Online :smile:

**Comment by graysonwright** [comment]
Great! Merged this in as 50860c9.

**Pull request closed without merging**
