### PR TITLE
Improve translations

### PR DESCRIPTION
**Pull request by pustomytnyk**

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Hey, you've added both Polish and Ukranian changes. Since I did the Polish copy, I have a feeling yours is an improvement.

What was the before/after? Are you able to describe why they weren't the right translation?

**Comment by pustomytnyk** [comment]
@BenMorganIO, sure. "Plecy" in Polish has only one literal meaning, a noun "shoulders", so that was quite funny translation :) The usual translation of "back" button in Polish is "Wstecz" ("backward") according to http://www.linguee.pl/angielski-polski/t%C5%82umaczenie/back+and+next+buttons.html

**Comment by BenMorganIO** [comment]
haha cool. What about the Ukrainian ones?

**Comment by pustomytnyk** [comment]
capitalized + action success messages with not changed meaning but a little shorter.

**Pull request merged**
