### PR TITLE
Enable Selectize for polymorphic fields

### PR DESCRIPTION
**Pull request by joanmc**
Use selectize for polymorphic fields as well as has many and belongs to fields

### CODE REVIEW

**Comment by pablobm** [comment]
Good call! There's one tiny detail though: the group names are not styled any differently from normal items by default. As a result, I feel it can be confusing.

selectize-optgroup

Would you be able to add some styling to fix this?

**Comment by pablobm** [comment]
Much better, thank you. Do you mind sorting those linter warnings, and we can then merge this?

**Comment by joanmc** [comment]
> Much better, thank you. Do you mind sorting those linter warnings, and we can then merge this?

My bad, missed those - should be good now 👍

**Review by pablobm — APPROVED** [review]
Great; thank you!

**Pull request merged**
