### PR TITLE
Allow customizing search fields with the SEARCH_ATTRIBUTES constant

### PR DESCRIPTION
**Pull request by FooBarWidget**
At the moment, a search works by querying all attributes. This is not always desirable. This patch allows you to customize the attributes that are used in the search.

This pull request depends on #383.

### CODE REVIEW

**Comment by maartenvanvliet** [comment]
:+1:

**Comment by pablocrivella** [comment]
+1

**Comment by FooBarWidget** [comment]
Hi maintainer, any updates on this?

**Comment by pustomytnyk** [comment]
Don't know what was the situation at the moment of PR, but now you can provide any field with "searchable" attribute, so the feature is already implemented.
https://github.com/thoughtbot/administrate/blob/5227c9bc5b20904155f419409d6c3606763d24a5/lib/administrate/field/deferred.rb#L24

**Comment by pablobm** [comment]
@pustomytnyk - You are correct. I'm closing this PR, but happy to see it reopen if I'm missing something.

**Pull request closed without merging**
