### PR TITLE
Add support for Rails 8.0

### LINKED ISSUE #2703: Rails 8.0 support
Hi, 
[Rails 8.0.0](https://rubygems.org/gems/rails/versions/8.0.0) has just been released yesterday (Nov 7th, 2024). I can see the `administrate.gemspec` has limited the ActiveRecord dependency to below 8.0 in December 2023. So, when I run `bundle install` with **Administrate 1.0.0-beta2** and **Rails 8.0**, I get a `Could not find compatible versions` error.

Can I ask when **Rails 8.0** will be supported please?

image

image

### PR DESCRIPTION
**Pull request by nickcharlton**
We needed to:

* Bring over quite a few things from `rails app:update`, which hopefully should make future upgrades easier,
* Fix a change to the `enum` `ActiveModel` signature, which changed between Rails 6.0 and 7.0,
* Add a version check from 7.0 for `raise_on_missing_callback_actions`,
* Make a few changes to CI (on top of #2712) to adjust the Ruby versions we run CI against.

https://rubyonrails.org/2024/11/7/rails-8-no-paas-required

Closes #2703

### CODE REVIEW

**Comment by nickcharlton** [comment]
So far, this is just a quick first-pass at opening up support, so we can make a little bit of progress with each additional change.

As of right now, we're stuck here, as `rails-i18n` is missing Rails 8.0 support: https://github.com/svenfuchs/rails-i18n/pull/1130

```
$ setup
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails60.gemfile' || bundle install --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails60.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails61.gemfile' || bundle install --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails61.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails70.gemfile' || bundle install --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails70.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails80.gemfile' || bundle install --gemfile='/Users/nickcharlton/projects/thoughtbot/administrate/gemfiles/rails80.gemfile' --retry 1
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Could not find compatible versions

Because rails-i18n < 0.1.6 depends on activesupport ~> 3
  and rails-i18n >= 0.1.6, < 4.0.0 depends on i18n ~> 0.5,
  rails-i18n < 4.0.0 requires activesupport ~> 3 or i18n ~> 0.5.
And because rails-i18n >= 4.0.0, < 4.0.6 depends on i18n ~> 0.6,
  rails-i18n < 4.0.6 requires activesupport ~> 3 or i18n >= 0.5, < 1.A.
And because rails-i18n >= 4.0.6, < 5.1.0 depends on i18n ~> 0.7
  and rails-i18n >= 5.1.0, < 6.0.0 depends on railties >= 5.0, < 6,
  rails-i18n < 6.0.0 requires activesupport ~> 3 or i18n >= 0.5, < 1.A or railties >= 5.0, < 6.
And because rails-i18n >= 6.0.0, < 7.0.1 depends on railties >= 6.0.0, < 7
  and activesupport >= 6.1.0 depends on i18n >= 1.6, < 2,
  if activesupport >= 6.1.0 and rails-i18n < 7.0.1 then railties >= 5.0, < 7.
And because rails-i18n >= 7.0.1 depends on railties >= 6.0.0, < 8
  and rails >= 8.0.0 depends on activesupport = 8.0.0,
  rails >= 8.0.0 requires railties >= 5.0, < 8.
So, because rails >= 8.0.0 depends on railties = 8.0.0
  and rails80.gemfile depends on rails ~> 8.0,
  version solving has failed.
```

**Comment by mpvosseller** [comment]
@nickcharlton looks like the `rails-i18n` gem has been updated & released. 🎉

**Comment by nickcharlton** [comment]
With `rails-i18n` released, I've been able to run through and do a bunch more of the Rails 8.0 upgrade.

I've done a bunch of it, now I'm going to wait for CI to fail and see what else we need to do.

**Comment by nickcharlton** [comment]
I'm left fighting with Ruby, Rails versions and testing the combination along with Appraisal on CI.

However, those are details in the scheme of getting this PR merged. If someone would like to test it out on their Rails 8.0 upgrade, feel free to go ahead — I'd be especially interested if there are any issues you see which might mean this takes longer than getting CI right.

**Comment by nickcharlton** [comment]
I'd started down the path of messing about with running Appraisals differently, because it was failing for various reasons. But remembered I'd actually started on this back in Feb as #2524.

I've now merged that, so we're back in Ruby vs. Rails expected compatibility.

It's time to drop some Ruby versions ahead of cutting the final version of v1, but unless this takes longer than today, I'd like to do that after this PR is merged. We'll see how it goes.

**Comment by januszm** [comment]
Failing specs are only for Ruby 3.1 and won't be possible to fix I guess:

```
activesupport-8.0.0 requires ruby version >= 3.2.0, which is incompatible with ...
```

To complete this PR we just might need to drop support for Ruby 3.1 in the next release? Can't wait for this PR to be merged

**Comment by nickcharlton** [comment]
I'd been trying a couple of different ideas for fixing CI — as it stands currently, I'm stuck on the following:

1. We need Appraisal to be installed to run `appraisal install`,
2. We can't bundle the main `Gemfile` because it won't support older versions of Ruby with the Rails 8 dependencies in place,
3. We can't run Appraisal outside the `Gemfile` because we hit other issues

I'm going to give it a little more time, but not much before giving in and dropping incompatible Rubies (I'm stubborn, but even that has limits!). We're so close to releasing a significant breaking change anyway (in v1) holding off dropping versions over 3 years old seems a bit much.

---

I was chatting with @louis-antonopoulos last night, who's working on a brand new Rails 8 application, which started off with Propshaft (as that's now the default). I'll open a new issue for this, but it's something we're going to have to do (but not necessarily in this PR).

**Comment by nickcharlton** [comment]
This is now ready to go. It took some re-thinking around CI, which I'm glad I did.

I'm going to merge this in tomorrow morning so I can take another look at it, but it's working fine so far.

**Comment by such** [comment]
Can this be released?

**Comment by nickcharlton** [comment]
I need to resolve #2715 first, then run through some regression tests. Then we can. It's in progress!

**Comment by januszm** [comment]
Thanks, I tested this branch in production for the past 2 weeks and didn't notice issues with deployments, so must be a bit minor

**Pull request merged**
