### PR TITLE
Allow to limit route actions

### PR DESCRIPTION
**Pull request by infertux**
This allows to limit route actions in `routes.rb` by using `only: [:index, :show]` for example and only display these routes in views.

### CODE REVIEW

**Comment by infertux** [comment]
Hmm so CircleCI is failing but I don't think it's related to my changes?

**Comment by BenMorganIO** [comment]
@infertux Rebuilding without cache :)

**Comment by infertux** [comment]
Ping @graysonwright @BenMorganIO :)

**Comment by BenMorganIO** [comment]
@infertux can you add specs for this please?

**Comment by infertux** [comment]
@BenMorganIO Sorry about the delay, I added specs.

BTW the build is failing because of bundler-audit.

**Comment by gee-forr** [comment]
I'd really love to see this feature make it into the main gem. Any chance of this getting approved? Is there anything I can do to help?

**Comment by BenMorganIO** [comment]
@infertux Could you rebase from master? That should green up the build :)

**Comment by nickcharlton** [comment]
This will cleanly rebase on `master` and I can't see any other issues, so I'm going to hit the magic button. Thanks for this!

**Pull request merged**
