### PR TITLE
WIP: Support Bourbon 5

### PR DESCRIPTION
**Pull request by graysonwright**
https://trello.com/c/ylP4P7vJ/88-bourbon-5-support

Failing specs courtesy of [Appraisal]

Might want to wait until we open-source this and get Percy.io set up
before merging, in order to make sure there are no breaking CSS changes.

[Appraisal]: https://github.com/thoughtbot/appraisal

### CODE REVIEW

**Comment by tysongach** [comment]
@graysonwright With #110 merged, can this be updated? Would love Bourbon 5 support.

**Comment by graysonwright** [comment]
@tysongach yep, this is unblocked now. I'll carve out some time this weekend to push this through.

**Comment by tysongach** [comment]
@graysonwright Any update here? I would love to offer some improvements to the styles in this codebase and Bourbon 5 would be very valuable.

**Comment by tysongach** [comment]
@graysonwright It looks like this is getting hung up because `datetime_picker_rails` calls on a `transition()` mixin ([here](https://github.com/graysonwright/datetime_picker_rails/blob/master/app/assets/stylesheets/datetime_picker/_component-animations.scss#L26)). Few issues with this:

- `transition()` is not a mixin that is defined within `datetime_picker_rails` itself
- `transition()` _is_ a mixin that is part of Bourbon (pre v5), but as far as I can tell, Bourbon is not a dependency
- This holds us back from using Bourbon 5 because it no longer as _any_ mixins for prefixes, `transition()` included in those deprecations
- Less of an issue, but something to note: the CSS `transition` property doesn’t really need to be prefixed anymore, as you can see with data over on Can I Use: http://caniuse.com/#feat=css-transitions

I put up a PR to `datetime_picker_rails`, which removes the `transition()` mixin: https://github.com/graysonwright/datetime_picker_rails/pull/4

**Comment by tysongach** [comment]
Updating `datetime_picker_rails` after we fixed and released the issues brought up above has now fixed these tests from failing. Bourbon 5 should be good to go.

**Comment by vcavallo** [comment]
Forgive me if I'm being dense, but is Bourbon 5 support definitely included now?

I'm using Bourbon `5.0.0.beta.7` and when I try to install administrate I get:

```
Bundler could not find compatible versions for gem "bourbon":
  In snapshot (Gemfile.lock):
    bourbon (= 5.0.0.beta.7)

  In Gemfile:
    bourbon (~> 5.0.0.beta.5)

    administrate was resolved to 0.3.0, which depends on
      bourbon (~> 4.2)
```

I tried this as well, thinking maybe I wasn't getting the correct version of administrate:

`gem "administrate", git: 'git@github.com:thoughtbot/administrate.git', branch: 'master'`

Is there something I'm missing that I must set/update in order to 'turn on' bourbon 5 support? Thanks!

**Comment by vcavallo** [comment]
Update: I'm sure I've clobbered this horribly, but I quickly (and admittedly without doing much research or testing) changed out all the instances of `bourbon` in [a fork](https://github.com/thoughtbot/administrate/compare/master...vcavallo:bourbon-5) and when I point my project's gemfile to this version I'm able to install and use administrate just fine.

**Comment by nickcharlton** [comment]
Hi @vcavallo!

From looking at it with fresh eyes, you're definitely correct. Would you open up a PR which does your change?

**Comment by vcavallo** [comment]
@nickcharlton Here it is, much delayed :)

https://github.com/thoughtbot/administrate/pull/759

**Pull request merged**
