### PR TITLE
Avoid singularizing namespace in Administrate::ResourceResolver

### PR DESCRIPTION
**Pull request by rmachielse**
See #1931 for details.

### CODE REVIEW

**Comment by rmachielse** [comment]
@pablobm what do you think? Does this have a chance of getting merged?

**Comment by pablobm** [comment]
@rmachielse - Would you be able to add an example to https://github.com/thoughtbot/administrate/blob/main/spec/lib/administrate/resource_resolver_spec.rb?

**Comment by rmachielse** [comment]
@pablobm would it be okay if I adapt the existing examples to use a plural namespace, like `admin/libraries/books`?

**Comment by pablobm** [comment]
@rmachielse - Wait, is there another way? :laughing: Go for it!

**Comment by rmachielse** [comment]
@pablobm example added!

**Comment by rmachielse** [comment]
Thank you!

**Pull request merged**
