### PR TITLE
Use manifest for precompiling assets with Sprockets 4

### PR DESCRIPTION
**Pull request by sorich87**
Administrate doesn't currently work with Sprockets 4 because regexes in precompile list are deprecated. This pull request fixes the issues by using a manifest.js.

### CODE REVIEW

**Comment by simon2k** [comment]
Could this be released?

**Comment by nickcharlton** [comment]
Hi @sorich87! I'd love to get this merged. Could you rebase on `master` or [enable contributor pushes](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)?

**Comment by sorich87** [comment]
@nickcharlton I enabled contributor pushes. Thanks!

**Comment by BenMorganIO** [comment]
Closing as #814 was merged.

**Comment by sorich87** [comment]
@benmorganio @nickcharlton #814 doesn't actually fix the issue as a manifest file is required by sprockets-rails https://github.com/rails/sprockets-rails/issues/369.

**Comment by nickcharlton** [comment]
Ooh, interesting.

So, reading that issue it looks like we need a `manifest.js` otherwise we're going to get a warning/error.

This comment suggests a (backwards compatible) possible solution, though: https://github.com/rails/sprockets-rails/issues/369#issuecomment-261925766

What do you think?

**Pull request closed without merging**
