### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by pusewicz**
This change introduces the Polish translation for the locale file.

### CODE REVIEW

**Comment by graysonwright** [comment]
Woohoo, thanks!

I'll definitely need help verifying this - anyone from the community want to give it their seal of approval?

**Comment by pkrefta** [comment]
@graysonwright It looks good and probably better than my translation pull request :)

**Comment by graysonwright** [comment]
Cool. Right now we're waiting on #172 before merging more PRs. I'll mark this as good to go for when we start merging again.

Thanks for the contribution!

**Comment by graysonwright** [comment]
Merged in as https://github.com/thoughtbot/administrate/commit/a61c16f390a68527025a28a60b641280674e2f0e. Thanks!

**Pull request closed without merging**
