### PR TITLE
Make Japanese translations more natural

### PR DESCRIPTION
**Pull request by shouichi**

### CODE REVIEW

**Comment by nickcharlton** [comment]
Could you have a look at the failing tests?

> Psych::SyntaxError: (/home/circleci/administrate/config/locales/administrate.ja.yml): found character that cannot start any token while scanning for the next token at line 8 column 22

**Comment by shouichi** [comment]
@nickcharlton Fixed the problem (sorry, opened this PR without testing :bow:

**Comment by nickcharlton** [comment]
No worries! It's all passing now so I'll merge this in.

**Comment by shouichi** [comment]
Thank you!

**Pull request merged**
