### PR TITLE
Add Indonesian locale

### PR DESCRIPTION
**Pull request by styd**
Hi! I want to add Indonesian to the list of locales. Thanks.

### CODE REVIEW

**Comment by nickcharlton** [comment]
Hi @styd! Thank you for your language contribution!

Something I'm trying to do is have someone keep maintaining the languages they contribute, because if one us doesn't speak it then they end up getting either left behind (and breaking the build), or filled in with not so great Google Translate answers. Do you think you'd be able to do this?

**Comment by styd** [comment]
Hi, @nickcharlton! I understand what you mean and I'm willing to maintain the Indonesian locale. I too want it to always be updated with the correct translations since I also use administrate in my project. So, if there are additions/changes in the locale please let me know.

[Here is an example of how I want Indonesian locale to be supported in another project](https://github.com/radar/humanize/issues/35). In short, I did some research to get the best possible translations and tried to ask a language expert about some unknown terms even though Indonesian is my native language.

**Comment by nickcharlton** [comment]
That sounds perfect! My main concern is ensuring that changes we make don't cause significant language regressions, so if you can watch out for changes and open new PRs if needed that'd be wonderful.

I'll go ahead and merge this now.

**Comment by styd** [comment]
Ok, will do. Thanks for merging.

**Pull request merged**
