### PR TITLE
Remove Neat

### PR DESCRIPTION
**Pull request by tysongach**
We are not really utilizing or in need of a full blown grid system.
Given that, and that this is an open-source project that is added to
existing projects, reducing this dependency offers nice benefits.

For now, this replaces Neat's mixins with properties to re-create a near
identical output. It would be a great next step to flesh out a *small*
class-based grid *system* for Administrate.

Related: https://github.com/thoughtbot/administrate/pull/789

### CODE REVIEW

**Comment by BenMorganIO** [comment]
:+1:

**Comment by BenMorganIO** [comment]
@tysongach I think you need to run `appraisal` over the project.

**Comment by tysongach** [comment]
@BenMorganIO I just ran it, but it produces no changes.

**Comment by BenMorganIO** [comment]
Ah, that's right! We don't commit the lockfile.

**Comment by nickcharlton** [comment]
Excellent! Could I get you to rebase this? (Perhaps after #868 is?)

**Comment by tysongach** [comment]
@nickcharlton Rebased.

**Comment by nickcharlton** [comment]
Since merging #389, this breaks on the Order page:

screen shot 2017-05-07 at 23 09 20

Setting the `margin-bottom` value throws off everything after that label. What's the best way around that?

**Comment by tysongach** [comment]
@nickcharlton Mind pulling down again and seeing if it is fixed now?

**Comment by nickcharlton** [comment]
Ah hah! That fixed it. Merging!

**Pull request merged**
