### PR TITLE
Update administrate.pt-BR.yml

### PR DESCRIPTION
**Pull request by lucianosousa**
removing intrusive `m` char

### CODE REVIEW

**Comment by lucianosousa** [comment]
up

**Comment by lucasrenan** [comment]
@lucianosousa build is failing 0.o

**Comment by lucianosousa** [comment]
@lucasrenan it's not related with this change.
Nokogiri warning (outdated gem)
maybe it was an issue 7 months ago

**Comment by nickcharlton** [comment]
Thanks! Merging.

**Pull request merged**
