### PR TITLE
Move app/views/fields/ to app/views/administrate/fields/

### PR DESCRIPTION
**Pull request by igorbozato**
Opening this PR to continue the discussion #973.
I moved `app/views/fields/` to `app/views/administrate/fields/` and renamed all references in the code and docs.

The only specs that broke was when `administrate-field-image` gem was used, which raises the question on how to handle backwards compatibility if we decide to move forwards with this change.

### CODE REVIEW

**Comment by nickcharlton** [comment]
This is looking good so far. Would you mind looking a the Hound comments and rebasing on current `master`?

I do agree we need to think about the backwards compatibility. Our releases are quite spread out at the moment, and we've been pre-`1.0.0` for a quite a while. So this makes me think that we should support the older style until we cross `1.0.0`.

The best way to do this might be to have a separate commit which gives us backwards compatibility (so a renaming one, then a backwards compatibility one), as it will help us remove it in the future. What do you think?

**Comment by purinkle** [comment]
@igorbozato, is this a change you would still like to make?

**Comment by pablobm** [comment]
Closing due to lack of activity 😞 Let us know if anyone wants to take over!

**Comment by madhums** [comment]
@pablobm would you be up for considering this PR if I reworked and supported backward compatibility?

**Comment by pablobm** [comment]
@madhums - I'm up for it. Would you be able to explain why you want it fixed, please?

**Pull request closed without merging**
