### PR TITLE
Remove dependency on sassc / scss

### PR DESCRIPTION
**Pull request by muriloime**
Hello there, 

I realized the sassc related gems are increasing our slug size in heroku by 10-20% so I decided to remove the (now deprecated) sassc dependencies. In the case this work is desirable by the maintainers, I am creating this PR 

cheers 
Murilo

### CODE REVIEW

**Comment by iainbeeston** [comment]
Any chance of hurrying this along? I have another reason for wanting this PR which is that I'm using Rails 7 with tailwind 3, and adding sassc into the mix causes tailwind to blow up with a `[Error: Function rgb is missing argument $green](https://github.com/tailwindlabs/tailwindcss/discussions/6738)` error (apparently due to sassc being old/out of date)

**Comment by muriloime** [comment]
@iainbeeston  this PR broke in production. I added a WIP

**Comment by muriloime** [comment]
I had a lot of sassc errors in my CI/CD server when running tests so I came back to this issue. 

I finally managed to remove sass. Unfortunately I had to change selectize-rails too, as it used .scss. 

I acknowledge it is maybe not the best way to use the asset pipeline (multiple files), but it is working now in prod \o/, and it does not rely on scss anymore.  I would be more than happy to discuss on how to improve the solution 

Cheers 
Murilo

**Comment by czepesch** [comment]
@muriloime hey!
I tried to deploy my app with Dokku using your fork, but have this error:
`-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       
       Done in 1389ms.
       rake aborted!
       LoadError: cannot load such file -- sassc`

I added //= link administrate_manifest.js to manifest,js

I also can't do `bundle exec rake assets:precompile` locally:
`rake aborted!
LoadError: cannot load such file -- sassc`
Any ideas? 
Thanks!

**Comment by muriloime** [comment]
> @muriloime hey! I tried to deploy my app with Dokku using your fork, but have this error: `-----> Preparing app for Rails asset pipeline Running: rake assets:precompile
> 
> ```
>    Done in 1389ms.
>    rake aborted!
>    LoadError: cannot load such file -- sassc`
> ```
> 
> I added //= link administrate_manifest.js to manifest,js
> 
> I also can't do `bundle exec rake assets:precompile` locally: `rake aborted! LoadError: cannot load such file -- sassc` Any ideas? Thanks!

Hey actually I had to modify [selectize](https://github.com/manuelvanrijn/selectize-rails) gem too ( and pointed the gem to [my github fork](https://github.com/muriloime/selectize-rails)). Very simple change, just changed the extension of the relevant files to me https://github.com/muriloime/selectize-rails/commit/130c59904d7b1605b6ae813b7cee462e5a6cc0c9.

**Comment by czepesch** [comment]
@muriloime I don't have this gem in my project and don't think I should use at all. If so, there is no way to make administrate work? or it is possible to make similar changes somewhere else?

**Comment by muriloime** [comment]
This gem is required by administrate

**Comment by sodabrew** [comment]
Kudos for this work, would be glad to see it land and reduce deploy sizes substantially

**Comment by MuhammetDilmac** [comment]
I think this pr has a urgent priority because of tailwind conflict. Have a expected release date?

**Comment by muriloime** [comment]
@MuhammetDilmac  @sodabrew  I don't know if this PR will ever see the light of day, as it required changes on other gems as well. I use this in production but I had to point to github versions of other gems. If some admin has an idea and are willing to release this change I am more than prone to discuss.

**Comment by sodabrew** [comment]
@muriloime was the only other change in `selectize-rails`? The version of Selectize used by `selectize-rails` is wildly out of date and looking at https://github.com/manuelvanrijn/selectize-rails, seems unlikely to be updated anytime. I would suggest removing it by importing selectize.js into this PR directly from https://github.com/selectize/selectize.js#installation

Comparing notes across projects, there is a Selectize plugin for ActiveAdmin: https://github.com/blocknotes/activeadmin_selectize (rather than using selectize-rails -- yet also uses sassc at runtime)

**Comment by pablobm** [comment]
Closing in favour of https://github.com/thoughtbot/administrate/issues/2311

**Pull request closed without merging**
