### PR TITLE
Freeze generated constants

### PR DESCRIPTION
**Pull request by teoljungberg**
By abiding to the thoughtbot styleguide,
We won't get any warnings from tools like Hound,
When opening a PR adding administrate to a project.

### CODE REVIEW

**Comment by teoljungberg** [comment]
The test failures are fixed in #512

**Comment by teoljungberg** [comment]
What's your take on this @graysonwright ?

**Comment by BenMorganIO** [comment]
:+1:

**Comment by graysonwright** [comment]
Alright, looks good to me.

**Comment by jondkinney** [comment]
This seems good on the surface. However, this removes the ability for us to add queries to the ATTRIBUTE_TYPES hash. Well, you can still add them, but only the objects present in the DB at the time of the app boot will show up, for example, in a select list. If I delete the `.freeze` then creating a new widget that I want to select on a different dashboard edit will have the full list. I realize this is "just how ruby/freeze works". Do you all have opinions on putting queries in the dashboard vs the generated form partial?

image

**Comment by jondkinney** [comment]
I updated my approach here and `.freeze` is no longer a problem. Instead of storing a query directly (which only gets executed on rails boot), I'm now instead storing a reference to a proc object that I later `.call` in the `_form.html.erb` template. I even wrapped it up in a gem called [administrate-field-collection_select](https://github.com/headwayio/administrate-field-collection_select). Hope it helps someone.

**Pull request closed without merging**
