### PR TITLE
Add translations for additional strings

### PR DESCRIPTION
**Pull request by buren**
This replaces #478. I had to do this since I removed my fork of administrate while that PR has been open and forking it again didn't "reattach" it to my fork.

### CODE REVIEW

**Comment by nickcharlton** [comment]
Great, thanks!

Could you drop your `Merge branch 'master'` commit and instead do a full rebase onto `master`? It adds a bunch of noise I'd like to try and keep out of the history.

I'm concerned that us putting English words in the translations for other languages might end up making us forget about those translations. What do you think about leaving them missing for now (whilst we wait to figure out what they should really be)?

**Comment by BenMorganIO** [comment]
@nickcharlton I'm thinking we split this guy out and into another gem for i18n. I would vote to wait to merge this guy until we get the translations into its own gem.

**Comment by buren** [comment]
Ok, I'll wait 👍

**Comment by BenMorganIO** [comment]
Can you `git rebase` this against master? There's updates for locales in master now.

**Comment by patriciomacadden** [comment]
Hello everyone! 😄 

I'd really like to get this gem merged. Is there a way I can help to get it done? - Don't want to go ahead and create a separate PR unless you say so.

PS: I can put together a PR with spanish translations once this one is merged.

**Comment by bronislav** [comment]
I've created #918 with partial duplication. Didn't notice this PR before.

What can I do to make this PR merge ASAP?

**Comment by buren** [comment]
@BenMorganIO should I go ahead and rebase this against `master` or are you guys till aiming for extracting `I18n` out to its own gem?

**Comment by BenMorganIO** [comment]
@buren I'm honestly not sure. I would recommend waiting. cc @nickcharlton

**Comment by nickcharlton** [comment]
Hi @buren! I'm not planning on doing that in the near future, but we will eventually.

I'd recommend you rebase, and then I think we can get this merged. If you'd also drop the "Merge commit", we'll have a tidy history and I can keep all of your commits, too.

**Comment by buren** [comment]
Finally got around updating/replacing this PR with something :)

See https://github.com/thoughtbot/administrate/pull/1004.

🛎 @nickcharlton

**Comment by nickcharlton** [comment]
Thanks! I'm going to close this for now and start looking over #1004.

**Pull request closed without merging**
