### PR TITLE
Fix hiding of search bar when none of searchable columns are used on index page

### PR DESCRIPTION
**Pull request by pustomytnyk**
Untie search from representation of collection

### CODE REVIEW

**Comment by nickcharlton** [comment]
Would you be able to add some tests to this?

**Comment by pustomytnyk** [comment]
@nickcharlton maybe after #843. It waits 20 days already.

**Comment by pustomytnyk** [comment]
@nickcharlton updated.

**Comment by nickcharlton** [comment]
It'd been a little while on this, so I took your branch and rebased. I'll merge it in now, thanks!

**Pull request merged**
