### PR TITLE
[BUGFIX] existing date values were being cleared

### LINKED ISSUE #135: DateTime fields blank out for values that are already set
Fields set as `Field::DateTime` seem to be automatically emptied out (rather than retaining their on-load value). Assuming this has something to do with the datepicker js, as it flashes the value for a moment presumably before the javascript executes.

### PR DESCRIPTION
**Pull request by graysonwright**
Fixes #135

## Problem:

When a user edits a resource
with a `Date`, `Time`, or `DateTime` attribute,
and the attribute already has a value,
the date-time picker clears out the value.

Unless the user re-fills the field,
the value will be reset and will cause an error
when they hit "submit".

## Solution:

Update the `datetimepicker` date format
to match the Rails default.

### CODE REVIEW

**Comment by graysonwright** [comment]
The build passes locally for me - will have to debug later this week.

**Comment by JoelQ** [comment]
LGTM once CI passes :package:

**Comment by jayroh** [comment]
Looks good here too, man.

**Comment by graysonwright** [comment]
Looks like this is an intermittently failing test. I ran `rspec --bisect -s 39930`, and got this minimal reproduction command:

```
rspec './spec/features/orders_form_spec.rb[1:2:1,1:3:1,1:3:2]' -s 39930
```

**Comment by graysonwright** [comment]
damn. it looks like that "minimal reproduction" passes. Will try to narrow it down again.

**Comment by graysonwright** [comment]
It looks like it's not dependent on test order or random seed - just luck. pretty strange... I wonder if master has the same problems, and we've just been lucky there so far.

**Comment by graysonwright** [comment]
Switching to poltergeist seems to do the trick.

**Pull request merged**
