### PR TITLE
Upgrade Administrate to work with Rails 5

### PR DESCRIPTION
**Pull request by teoljungberg**
This PR upgrades Administrate to work with Rails 5. The changes
are backwards compatible to Rails 4.2 which we support.

Changes:
- Set `active_record.time_zone_aware_types` for Rails 5.
- Replace `column_types`
  It was removed in [the following commit to rails/rails]

  [the following commit to rails/rails]: https://github.com/rails/rails/commit/70ac072976c8cc6f013f0df3777e54ccae3f4f8c.

- "Sanitize" order parameters to quell warnings.
- Add HTTP method shims
  This provides backwards compatibility from Rails 5 to 4.
  
  Inspiration:
  - https://github.com/thoughtbot/clearance/pull/639
  - https://github.com/thoughtbot/high_voltage/pull/229/files

- Configure serving public assets to work with Rails 4 and 5.
- Only set `raise_in_transactional_callbacks` if < Rails 5.
  The option is deprecated in Rails 5.

- Upgrade `ActionController` configuration for Rails 5
- Remove unused spec helper
- Only remove the XML parser if < Rails 5
- Add appraisals for rails 4.2 and 5.0.
  Add binstub for appraisal.

- Lax Rails version requirement.
  Lock in `4.2 < Rails::VERSION < 5.1`.

- Use [fork] of `administrate-field-image`.
  Which relaxes the version requirement for Rails.
  [fork]: https://github.com/graysonwright/administrate-field-image/pull/5

- Upgrade `rspec-rails`

### CODE REVIEW

**Comment by maxehmookau** [comment]
Any idea on when this might get merged? Administrate is great but missing Rails 5 support is a big issue right now. :(

**Comment by towen** [comment]
Really looking forward to getting this PR pushed thru. Thanks for all your work on it @maxehmookau

**Comment by m-o-e** [comment]
There seem to be multiple independent Rails5 PRs and forks by now.

Could one of the administrate maintainers please signal
_which_ PR is going to be merged and when?

**Comment by preist** [comment]
🎉

**Comment by j-dexx** [comment]
@danbee How close is a version release to rubygems that includes rails 5?

**Comment by imajes** [comment]
1. Why was this PR picked over other Rails 5 PRs?

2. The build fails with this PR. 👎 👎 👎 

3. Using a `.find` on `column_types`? That's pretty lazy. 👎 👎 👎 

4. As far as i can tell, changing the config for `action_on_unpermitted_parameters` to `:log` is simply lazy and insecure. wtf? 😡 😡 😡

**Comment by danbee** [comment]
@imajes:

1. Because it was.

2. The build fails on CI right now due to some weirdness with bundler. The build passes locally now.

3. Please feel free to submit a PR with a better approach.

4. You're right. This has been dealt with.

You made a couple of valid points here, but I'd appreciate it if you were less rude next time. Thanks.

**Pull request merged**
