### PR TITLE
Update administrate-field-image to release

### PR DESCRIPTION
**Pull request by nickcharlton**

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@nickcharlton What if you update bundler to `1.13.7` in `circle.yml` and `Gemfile.lock`? The error message seems like some bundler version conflict, no?

**Comment by nickcharlton** [comment]
@deivid-rodriguez Yep! That's the solution. I've just run out of time for now.

It'd be nice to not have it break on each new release of `bundler`, but that's a problem for another time.

**Comment by nickcharlton** [comment]
And fixed. It was the Circle cache, but updating bundler was a good idea anyway.

**Comment by deivid-rodriguez** [comment]
:tada:

**Pull request merged**
