### PR TITLE
Custom field search

### PR DESCRIPTION
**Pull request by pablobm**
Supersedes https://github.com/thoughtbot/administrate/pull/1006, which needed a rebase and some conflict fixing.

### CODE REVIEW

**Comment by dare05** [comment]
@pablobm When do you guys plan to integrate this into the new release? I think it's an essential feature, and the only thing that stops me from fully adopting administrate in production (I have tables with fields like "exp_date" I often need to do a search by, and currently I can't seem to find a way to do it with the current release).

**Comment by pablobm** [comment]
We expect this to go in the next release, although we cannot guarantee a date for this.

There's a way to work around this though. In your Gemfile, you can tell Bundler to use this specific branch of the project with the following declaration:

```
gem 'administrate', git: 'https://github.com/thoughtbot/administrate', branch: 'custom_field_search'
```

I hope that helps.

**Comment by dsolomadin** [comment]
Why no changes to the documentation? @pablobm

**Comment by dare05** [comment]
@pablobm don't need an exact date, but can you at least provide a range? Like somewhere between March and May, for eg.

**Comment by nickcharlton** [comment]
@pablobm Could I get you to rebase when you get a chance? And also add some docs, too.

@dare05 As I only did `0.9.0` relatively recently, I think we're probably looking at the end of March/ start of April. I'm keen to improve our release cadence, as so many people end up bundling from `master` which is less than ideal (last time was a big gap).

**Comment by pablobm** [comment]
@nickcharlton - I haven't had much of a chance. I'm hoping to look into it this coming Friday.

**Comment by pablobm** [comment]
@dare05 I am having second thoughts about this code, and I would like to revisit it. In the mean time, would https://github.com/thoughtbot/administrate/pull/1131 serve your purpose? Please let me know of use cases and possible problems. Thank you.

**Comment by nickcharlton** [comment]
@pablobm What are you thinking about this now? I've merged in #1131 and that'll go out in a release soon.

**Comment by pablobm** [comment]
@nickcharlton - I'm going to close this one. I want to revisit it.

**Pull request closed without merging**
