### PR TITLE
Fix German grammar errors

### PR DESCRIPTION
**Pull request by clemensg**
Fix grammar errors in the German translations.

### CODE REVIEW

**Comment by graysonwright** [comment]
Thanks!

Can someone from the community verify these changes?

**Comment by mhelmetag** [comment]
In German, nouns and pronouns are capitalized so this looks good to me. Also, at least in terms of the update to `has_one`'s `not_supported` [error message](https://github.com/thoughtbot/administrate/pull/307/files#diff-2a4193ec3ebf05d4dd889ff9723a0679L21), `polymorphism`'s has Beziehungen already capitalized so this PR looks like it's just getting the nouns and pronouns all nice and uniform. Hope that helps at all.

**Comment by clemensg** [comment]
I'm a native speaker, by the way.

We could also translate HasOne relationship (to "Eins-zu-eins Beziehung") but that would probably be more confusing for developers, it's often better to keep technical keywords in English, in my opinion.

**Comment by graysonwright** [comment]
Sounds good.

Merged this in as b4dfd34. Thanks!

**Pull request closed without merging**
