### PR TITLE
Add show option to HasMany, to control child record columns

### LINKED ISSUE #1108: Allow for custom attributes on PageCollection
This will allow fixing https://github.com/nickcharlton/administrate-field-nested_has_many/issues/12 and improving `NestedHasMany` capabilities.

Let me know if there are any restraints on this change or if there are alternative methods. If it's okay, I can go ahead and work on this.

### PR DESCRIPTION
**Pull request by jmmastey**
- adds a new `show` option to HasMany, an array that controls displayed
  columns
- when that option _is_ forwarded, respects it within the collection
  page object
- updates docs to expose the new option

The tests are pretty reasonable, with one reasonable exception: the new HasMany test is really mockist, which I can see other tests are not. If y'all have a more reasonable approach to testing that bit of logic, I'm game. I tried and ended up just asserting a bunch of trivial behavior.

Fixes #1108 and #1109

### CODE REVIEW

**Comment by badosu** [comment]
@jmmastey If you want I can send a PR for your fork to fix those issues so that we can have this merged.

**Comment by jmmastey** [comment]
@badosu sounds great to me

**Comment by badosu** [comment]
@jmmastey Thanks, there it is: https://github.com/jmmastey/administrate/pull/1

**Comment by badosu** [comment]
Ok, one last change, I'll submit later today.

**Comment by badosu** [comment]
@nickcharlton Is there a way to run the same check Hound CI is doing on the development environment?

**Comment by badosu** [comment]
@jmmastey I submitted https://github.com/jmmastey/administrate/pull/2, it also fixes an issue of the added tests that need to consider additional arguments that are passed now since your first PR.

**Comment by badosu** [comment]
Thanks @jmmastey!

@nickcharlton If you can review or suggest someone to review, this PR is ready!

**Comment by stratigos** [comment]
Im not sure if Im following this change correctly, but would it also resolve #1191 - using the association's collection attrs instead of the current models collection attrs (when rendering paginated nested associations)?

**Comment by brentkearney** [comment]
Will this "show" option also work for Field::BelongsTo? That would be nice. :)

**Comment by jmmastey** [comment]
@brentkearney Good question! tbh, this pull is almost a year old with no reply by any maintainer, so I'm not inclined to test. At first glance it looks like it does?

**Comment by Branksy** [comment]
@badosu @jmmastey Has 1152 been merged? I'm having no luck customizing child record columns.

**Comment by sebasdeldi** [comment]
Same here, would really appreciate this getting merged

**Comment by mostlyerror** [comment]
Does anyone have a current workaround?

**Comment by badosu** [comment]
I am not using administrate anymore

**Comment by mostlyerror** [comment]
@badosu out of curiosity -- what are you using?

**Comment by badosu** [comment]
@mostlyerror Depend on the project, currently active admin.

**Pull request closed without merging**
