### PR TITLE
Fix ordering HasOne fields without explicit order

### PR DESCRIPTION
**Pull request by mikz**
This fixes a bug in awesome https://github.com/thoughtbot/administrate/pull/2325.

Ordering by a primary key of the HasOne field wasn't working
and resulted in invalid sql, because it did not join the associated table.

This unifies the code paths to use the same logic to add the ordering
from another table and use reflection to get relevant table information.

### CODE REVIEW

**Comment by mikz** [comment]
@nickcharlton looks like even after https://github.com/thoughtbot/administrate/pull/2498 approval is needed to run the workflow in a fork. Could I get approval from someone?

**Comment by shouichi** [comment]
I also encountered this problem. I tried this PR locally and it worked as expected :+1:

**Comment by nickcharlton** [comment]
> @nickcharlton looks like even after https://github.com/thoughtbot/administrate/pull/2498 approval is needed to run the workflow in a fork

Yeah, this is, unfortunately, expected behaviour. That PR allowed running _at all_, but then you need a maintainer (or equivalent, I don't remember the default roles off the top of my head) to approve them to run. The intention is to protect against data exfil, I think, or using lots of compute, maybe? It doesn't really apply to this project, so it's just another hurdle to have to jump over.

**Comment by mikz** [comment]
@nickcharlton yeah, I understand. But can you approve it, so we can get a build and merge this fix?

**Review by nickcharlton — APPROVED** [review]
I've tried to finish reviewing this 4 four times, but kept getting pulled away 🤦.

Anyway, this looks good, thanks!

**Comment by mikz** [comment]
@nickcharlton Thank you very much! 🎉

**Pull request merged**
