### PR TITLE
relax rails dependencies from < 5.2 to < 6.0

### LINKED ISSUE #1133: Dependency issues with rails 5.2.0 on bundle install
**Expected:**
Should be able to add administrate gem to Rails 5.2.0 project.

**Actual**
Error resolving dependencies and could not run `bundle install`.

**Steps to Reproduce**
1. Add administrate gem to a 5.2.0 rails app Gemfile via `gem 'administrate', '~> 0.9.0'`
2. run `bundle install` in console

**Error Message**
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    administrate (~> 0.9.0) was resolved to 0.9.0, which depends on
      actionpack (< 5.2, >= 4.2)

    rails (= 5.2.0) was resolved to 5.2.0, which depends on
      actionpack (= 5.2.0)
```

**Suggested fix**
Set actionpack dependency to `actionpack (~> 5.2.0, >= 4.2)`

**Isolated Issue**
I added administrate gem to a 5.1.6 rails app and dependencies were resolved and `bundle install` ran successfully

PS. Thank you for being awesome and all the work you do thoughtbot team :) !

### PR DESCRIPTION
**Pull request by Tongboy**
fixes #1133

### CODE REVIEW

**Comment by mactkg** [comment]
Development rails 6.0 have been already started, so it should be better to change a version to Rails < 6.0.

https://github.com/rails/rails/commit/1c383df324fdf0b68b3f54a649eb7d2a4f55bcb7

**Comment by Tongboy** [comment]
@mactkg I'd agree with that - I was going for the pessimistic option in case there were some ties to internal hooks - I didn't see any when I skimmed through the code.

updated to relax to < 6.0

**Comment by krainboltgreene** [comment]
These failures are due to rspec no longer allowing you to top level `params:` values.

**Comment by gsamokovarov** [comment]
I'd say, even relax the upper bound. Rails is much more stable these days and those upper bounds in the plugins are major pain point between updates. I have a really small app that uses administrate and cannot upgrade it to `5.2` stable at the moment.

**Comment by jnarowski** [comment]
+1 trying to upgrade to rails 5.2 also.

**Comment by bingxie** [comment]
+1 trying to upgrade to rails 5.2 also.

**Comment by nickcharlton** [comment]
Thank you for putting in the effort to open this! I'm going to close this in favour of #1148, as the tests are passing there.

**Pull request closed without merging**
