### PR TITLE
Added several hook points in the layout file

### PR DESCRIPTION
**Pull request by goosys**
Added several hook points for customization.
This simplifies the process of adding elements to parts of the page, allowing for customization without the need to copy existing templates.

### CODE REVIEW

**Comment by nickcharlton** [comment]
Thanks! Could you add a section [to the docs](https://github.com/thoughtbot/administrate/tree/main/docs) to cover this addition?

**Comment by goosys** [comment]
@nickcharlton Thank you for the review!
I’ve added the docs, but how does it look? Please feel free to point out any suggestions for the location or wording if needed.

**Review by nickcharlton — COMMENTED** [review]
This looks good, thanks!

Just a few Markdown points.

**Comment by goosys** [comment]
@nickcharlton 
Thank you for the review. I have addressed the points you mentioned.

**Comment by nickcharlton** [comment]
Great, thanks!

**Pull request merged**
