### PR TITLE
Adds translated resources to page titles and call to action buttons

### PR DESCRIPTION
**Pull request by mauriciozaffari**

### CODE REVIEW

**Comment by nickcharlton** [comment]
Is your intention with this PR to introduce translated page titles and call to action buttons, or a new date field?

**Comment by mauriciozaffari** [comment]
Hi Nick,

The initial intent was to introduce the translations. Then I needed the Date field and ended up doing it in the same branch, since I'm using my fork on my project. I can work on splitting those 2 into separated PR's if needed.

**Comment by nickcharlton** [comment]
If you could split out the date field, that'd be great! I'll take a look at it properly then.

**Comment by pablobm** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
