### PR TITLE
Add resource/attribute name to table haders

### PR DESCRIPTION
**Pull request by shouichi**
Close https://github.com/thoughtbot/administrate/issues/2068.

### CODE REVIEW

**Comment by pablobm** [comment]
Works for me :-) Thank you!

**Comment by shouichi** [comment]
@pablobm Thank you for all the hard work of administrate! It's been super beneficial for us. I would appreciate is you cut a new release :)

**Comment by pablobm** [comment]
@shouichi - Unfortunately that's not in my power, but I have pinged the appropriate people.

**Comment by shouichi** [comment]
Thank you so much!

**Pull request merged**
